default_settings: null
behaviors:
  CarBehavior:
    trainer_type: ppo
    hyperparameters:
      batch_size: 1024               # Number of samples in each training batch
      buffer_size: 10240             # Size of the experience buffer (10x batch size is common)
      learning_rate: 3.0e-4          # Learning rate for gradient updates
      beta: 5.0e-4                   # Strength of entropy regularization to encourage exploration
      epsilon: 0.2                   # Clipping parameter for PPO to maintain stable updates
      lambd: 0.95                    # GAE (Generalized Advantage Estimation) lambda
      num_epoch: 5                   # Number of passes through the buffer during gradient updates
      learning_rate_schedule: linear # Gradually decreases learning rate during training
    network_settings:
      normalize: true                # Normalize input observations for stability
      hidden_units: 128              # Number of units in each hidden layer of the network
      num_layers: 2                  # Number of layers in the neural network
    reward_signals:
      extrinsic:
        gamma: 0.99                  # Discount factor for rewards
        strength: 1.0                # Weight of the extrinsic reward
    max_steps: 10000000                # Total training steps
    time_horizon: 64                 # Number of steps collected in the trajectory before adding to buffer
    summary_freq: 20000              # Frequency (in steps) to log summaries to TensorBoard
    checkpoint_interval: 100000      # Save checkpoints only at the end of training
    keep_checkpoints: 10              # Maximum number of recent checkpoints to keep
    threaded: false                  # Disable threading for reproducibility
env_settings:
  # env_path: auto                   # Auto-detect the environment path
  env_args: null                     # No additional environment arguments
  base_port: 5005                    # Port for communicating with the Unity environment
  num_envs: 1                        # Number of parallel environment instances
  num_areas: 1                       # Number of simulation areas (relevant for multi-agent setups)
  timeout_wait: 60                   # Time (in seconds) to wait for the environment to respond
  seed: -1                           # Random seed for reproducibility (-1 for random seed)
  max_lifetime_restarts: 10          # Maximum number of restarts for the environment
  restarts_rate_limit_n: 1           # Rate limit for environment restarts (number of retries)
  restarts_rate_limit_period_s: 60   # Rate limit period in seconds
engine_settings:
  width: 84                          # Width of the rendered environment
  height: 84                         # Height of the rendered environment
  quality_level: 5                   # Graphics quality level
  time_scale: 20                     # Time scale of the simulation for faster training
  target_frame_rate: -1              # No limit on target frame rate
  capture_frame_rate: 60             # Frame rate for capturing video during simulation
  no_graphics: true                  # Disable graphics for faster training
  no_graphics_monitor: true          # Disable the graphics monitor
environment_parameters: null         # No additional environment parameters
checkpoint_settings:
  run_id: TrainRun02_25E             # Unique ID for this training run
  initialize_from: null              # No pre-trained model to initialize from
  load_model: false                  # Start training from scratch
  resume: false                      # Do not resume training from a previous run
  force: true                        # Overwrite existing models and results if they exist
  train_model: true                  # Enable training
  inference: false                   # Disable inference-only mode
  results_dir: results               # Directory to store training results
torch_settings:
  device: "cuda:0"                      # Use default device (auto-detect CPU/GPU)
debug: false                         # Disable debug mode for performance
