torch_settings:
  device: cuda:0

behaviors:
  CarBehavior:
    trainer_type: sac
    hyperparameters:
      batch_size: 256
      buffer_size: 1000000
      buffer_init_steps: 1000
      learning_rate: 3.0e-4
      learning_rate_schedule: constant
      tau: 0.005
      steps_per_update: 1
      init_entcoef: 0.5
      save_replay_buffer: false
    network_settings:
      num_layers: 3
      hidden_units: 512
      normalize: true
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    keep_checkpoints: 10
    max_steps: 5000000
    time_horizon: 64
    summary_freq: 25000
    checkpoint_interval: 1000000
    threaded: true

environment_parameters:
  obstacle_spawn_rate:
    curriculum:
      - name: "Lesson0"
        completion_criteria:
          measure: progress
          behavior: CarBehavior
          threshold: 0.1
        value: 0.0
      - name: "Lesson1"
        completion_criteria:
          measure: progress
          behavior: CarBehavior
          threshold: 0.3
        value: 0.3
      - name: "Lesson2"
        value: 0.6
  obstacle_speed_multiplier:
    curriculum:
      - name: "Lesson0"
        completion_criteria:
          measure: progress
          behavior: CarBehavior
          threshold: 0.1
        value: 0.8
      - name: "Lesson1"
        completion_criteria:
          measure: progress
          behavior: CarBehavior
          threshold: 0.3
        value: 1.2
      - name: "Lesson2"
        value: 1.5